/*
 * Algorithmgui.java
 *
 * Created on 29 November 2008, 20:37
 */

package algorithmgui;


import algorithmgui.InsertionSort;
import javax.swing.JTextField;


/**
 *
 * @author  Rajin Madahar
 */
public class Algorithmgui extends javax.swing.JFrame {

    JTextField value = new JTextField(16);
    private JTextField inputField;
    
    
    /** Creates new form Algorithmgui */
    public Algorithmgui() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ArrayLTextField = new javax.swing.JTextField();
        ArrayLimTextField = new javax.swing.JTextField();
        SearchTarTextxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        InsertionSortButton1 = new javax.swing.JButton();
        BinarySearchButton2 = new javax.swing.JButton();
        QuickSortButton3 = new javax.swing.JButton();
        MergeSortButton4 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        ArrayLTextField.setText(ArrayLTextField.getText());
        ArrayLTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArrayLTextFieldActionPerformed(evt);
            }
        });

        ArrayLimTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArrayLimTextFieldActionPerformed(evt);
            }
        });

        SearchTarTextxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTarTextxtFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Array Size");

        jLabel3.setText("Enter Array Limit");

        jLabel4.setText("Enter Search Target");

        InsertionSortButton1.setText("InsertionSort");
        InsertionSortButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertionSortButton1ActionPerformed(evt);
            }
        });

        BinarySearchButton2.setText("BinarySearch");
        BinarySearchButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BinarySearchButton2ActionPerformed(evt);
            }
        });

        QuickSortButton3.setText("QuickSort");
        QuickSortButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuickSortButton3ActionPerformed(evt);
            }
        });

        MergeSortButton4.setText("MergeSort");
        MergeSortButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MergeSortButton4ActionPerformed(evt);
            }
        });

        jLabel6.setText("Time in nanoseconds");

        jScrollPane1.setViewportView(jTextPane1);

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jTextPane2);

        jScrollPane3.setViewportView(jTextPane3);

        jLabel5.setText("Unsorted Array");

        jLabel7.setText("Sorted Array");

        jLabel8.setText("Binary Search Target");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(ArrayLTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ArrayLimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(126, 126, 126)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(SearchTarTextxtField)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(455, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                        .addGap(389, 389, 389))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(462, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BinarySearchButton2)
                        .addContainerGap(468, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(501, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(InsertionSortButton1)
                        .addGap(130, 130, 130)
                        .addComponent(QuickSortButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addComponent(MergeSortButton4)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchTarTextxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArrayLTextField)
                    .addComponent(ArrayLimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertionSortButton1)
                    .addComponent(QuickSortButton3)
                    .addComponent(MergeSortButton4))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(BinarySearchButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
       /**
      *
      * @author  harj
      */ 
    
    
    private void BinarySearchButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BinarySearchButton2ActionPerformed
                                                    
         int ArrayLimit = Integer.parseInt(ArrayLimTextField.getText());
         int ArraySize = Integer.parseInt(ArrayLTextField.getText());
         int SearchTarget = Integer.parseInt(SearchTarTextxtField.getText());
         long bStart, bEnd, bElapsed;
         int [] Array2 = ArrayUtil.randomIntArray(ArraySize, ArrayLimit);    
         
         StringBuilder builder1 = new StringBuilder(Array2.length);
                 for (int i=0 ;i<Array2.length;builder1.append(Array2[i++])) builder1.append(" ");
                           jTextPane2.setText(builder1.toString()); 
                         
         InsertionSort.InsertionSort(Array2,ArraySize);                 
     
         StringBuilder builder2 = new StringBuilder(Array2.length);
                 for (int i=0 ;i<Array2.length;builder2.append(Array2[i++])) builder2.append(" ");
                           jTextPane1.setText(builder2.toString());  
         
         bStart = System.nanoTime(); // calculates time                                
         binary.binarySearch(Array2, 0 , Array2.length -1,SearchTarget);
         bEnd = System.nanoTime(); // Sets the time to nano seconds
         bElapsed = bEnd - bStart;  // Calculates the time taken by binary search 
                           jTextField1.setText("The Binary Search algorithm took: - " + bElapsed + " nanoseconds"); // Prints out the time taken
                         
         
         
         
         int index = binary.binarySearch(Array2, 0 , Array2.length -1,SearchTarget);
      
         if(index != -1)   
                           jTextPane3.setText("Value "+SearchTarget+" found || index= " + index);    //print the search number and index of element
                    else {                                                               //otherwise,
                           jTextPane3.setText("Value "+SearchTarget+" not found");
       }  
}//GEN-LAST:event_BinarySearchButton2ActionPerformed

    
    private void QuickSortButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuickSortButton3ActionPerformed
        
         int ArrayLimit = Integer.parseInt(ArrayLimTextField.getText());
         int ArraySize = Integer.parseInt(ArrayLTextField.getText());
         int [] Array3 = ArrayUtil.randomIntArray(ArraySize, ArrayLimit);    
         long qStart, qEnd, qElapsed; // declaring the variable
         
         StringBuilder builder = new StringBuilder(Array3.length);
                 for (int i=0 ;i<Array3.length;builder.append(Array3[i++])) builder.append(" ");
                            jTextPane2.setText(builder.toString());
                            
         qStart = System.nanoTime(); // records times                                
         quickSort.quickSort(Array3, 0 , Array3.length -1);
         qEnd = System.nanoTime(); // Claculates time in nano seconds
         qElapsed = qEnd - qStart; // calculates time   
                            jTextField2.setText("The Quick Sort algorithm took: - " + qElapsed + " nanoseconds"); // prints the time taken
         
         StringBuilder builder2 = new StringBuilder(Array3.length);
                 for (int i=0 ;i<Array3.length;builder2.append(Array3[i++])) builder2.append(" ");
                            jTextPane1.setText(builder2.toString()); 
}//GEN-LAST:event_QuickSortButton3ActionPerformed

    
    private void InsertionSortButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertionSortButton1ActionPerformed
     int ArrayLimit = Integer.parseInt(ArrayLimTextField.getText());
          int ArraySize = Integer.parseInt(ArrayLTextField.getText());
          int [] Array = ArrayUtil.randomIntArray(ArraySize, ArrayLimit); 
          long iStart, iEnd, iElapsed;
          
          StringBuilder builder = new StringBuilder(Array.length);
                 for (int i=0 ;i<Array.length;builder.append(Array[i++])) builder.append(" ");
                            jTextPane2.setText(builder.toString());  
                                     
          iStart = System.nanoTime(); // records times
          InsertionSort.InsertionSort(Array,ArraySize);
          iEnd = System.nanoTime(); // Claculates time in nano seconds
          iElapsed = iEnd - iStart; // calculates time       
                            jTextField4.setText("The Insertion Sort algorithm took: - " + iElapsed + " nanoseconds"); // prints the time taken
      
          StringBuilder builder2 = new StringBuilder(Array.length);
                 for (int i=0 ;i<Array.length;builder2.append(Array[i++])) builder2.append(" ");
                            jTextPane1.setText(builder2.toString());  
   
    {                             }
     
}//GEN-LAST:event_InsertionSortButton1ActionPerformed

    private void MergeSortButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MergeSortButton4ActionPerformed
       
        int ArrayLimit = Integer.parseInt(ArrayLimTextField.getText());
        int ArraySize = Integer.parseInt(ArrayLTextField.getText());
        int [] Array4 = ArrayUtil.randomIntArray(ArraySize, ArrayLimit);  
        long mStart, mEnd, mElapsed;
           
        StringBuilder builder = new StringBuilder(Array4.length);
                 for (int i=0 ;i<Array4.length;builder.append(Array4[i++])) builder.append(" ");
                            jTextPane2.setText(builder.toString());                   
                            
        mStart = System.nanoTime(); // calculates time   
        MergeSort.mergeSort_srt(Array4, 0 , Array4.length -1);
        mEnd = System.nanoTime(); // Sets the time to nano seconds
        mElapsed = mEnd - mStart;  // Calculates the time taken by binary search 
                            jTextField3.setText("The Merge Sort algorithm took: - " + mElapsed + " nanoseconds"); // prints the time taken
           
        StringBuilder builder2 = new StringBuilder(Array4.length);
                 for (int i=0 ;i<Array4.length;builder2.append(Array4[i++])) builder2.append(" ");
                            jTextPane1.setText(builder2.toString());                          
}//GEN-LAST:event_MergeSortButton4ActionPerformed

    private void ArrayLTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArrayLTextFieldActionPerformed
int ArraySize = Integer.parseInt(ArrayLTextField.getText());



}//GEN-LAST:event_ArrayLTextFieldActionPerformed

    private void ArrayLimTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArrayLimTextFieldActionPerformed
int ArrayLimit = Integer.parseInt(ArrayLimTextField.getText());
}//GEN-LAST:event_ArrayLimTextFieldActionPerformed

    private void SearchTarTextxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTarTextxtFieldActionPerformed
int SearchTarget = Integer.parseInt(SearchTarTextxtField.getText());
}//GEN-LAST:event_SearchTarTextxtFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    



        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Algorithmgui().setVisible(true);           
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ArrayLTextField;
    private javax.swing.JTextField ArrayLimTextField;
    private javax.swing.JButton BinarySearchButton2;
    private javax.swing.JButton InsertionSortButton1;
    private javax.swing.JButton MergeSortButton4;
    private javax.swing.JButton QuickSortButton3;
    private javax.swing.JTextField SearchTarTextxtField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    // End of variables declaration//GEN-END:variables
    
}
